version: '3.7'

services:
  pdns-rec:
#    image: lostlink/pdns-rec:4.9
    build:
      context: .
    hostname: ns3.pdns.test
    environment:
      - TZ=UTC
      - PDNS_config_dir=/etc/pdns
      - PDNS_setuid=recursor
      - PDNS_setgid=recursor
      - PDNS_local_port=${PDNS_PORT:-53}
    ports:
      - "${FORWARD_PDNS_TCP_PORT:-53}:${PDNS_PORT:-53}/tcp"
      - "${FORWARD_PDNS_UDP_PORT:-53}:${PDNS_PORT:-53}/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
