version: '3.7'

services:
  octane:
    build:
      context: .
      args:
        - PACKAGIST_TOKEN=${PACKAGIST_TOKEN}
        - DOTENV_TOKEN=${DOTENV_TOKEN}
        - APP_ENV=develop
    environment:
      - APP_ENV=develop
      - ENABLE_HORIZON=true
      - ENABLE_SCHEDULER=true
    ports:
      - "${FORWARD_APP_PORT:-9000}:${OCTANE_APP_PORT-9000}"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  horizon-worker:
    build:
      context: .
      args:
        - PACKAGIST_TOKEN=${PACKAGIST_TOKEN}
        - DOTENV_TOKEN=${DOTENV_TOKEN}
        - APP_ENV=develop
    environment:
      - APP_ENV=develop
      - HORIZON_WORKER=true
    ports:
      - "${FORWARD_APP_PORT:-9000}:${OCTANE_APP_PORT-9000}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
