version: '3.7'

volumes:
  mysql:

services:
# TODO: Add Local dynamodb for easy offline setup
#  dynamodb:

  caddy-octane:
    build:
      context: .
    hostname: caddy-octane.domainlink.test
# TODO: Enable dynamodb dependency once the service is added to the compose file
#    depends_on:
#      - dynamodb
    environment:
      - DOMAIN_API_CHECK_URL=${DOMAIN_API_CHECK_URL}
      - POWERDNS_SERVER_URL=${POWERDNS_SERVER_URL}
      - POWERDNS_API_TOKEN=${POWERDNS_API_TOKEN}
      - LETS_ENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "${FORWARD_CADDY_ADMIN_PORT:-2019}:${CADDY_ADMIN_PORT:-2019}"
      - "${FORWARD_CADDY_HTTP_PORT:-2080}:${CADDY_HTTP_PORT:-2080}"
      - "${FORWARD_CADDY_HTTPS_PORT:-2443}:${CADDY_HTTPS_PORT:-2443}"
      - "${FORWARD_APP_PORT:-9000}:${OCTANE_APP_PORT:-9000}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
