# API Support
[api]
enabled = true
address = "0.0.0.0:8686"

# TCP source for incoming JSON data
[sources.socket_tcp]
type = "socket"
address = "0.0.0.0:9001"
mode = "tcp"
max_length = 1024000

# UDP source for incoming JSON data
[sources.socket_udp]
type = "socket"
address = "0.0.0.0:9002"
mode = "udp"
max_length = 1024000

# Kinesis sink with dynamically set stream name and region
[sinks.kinesis_dynamic]
type = "aws_kinesis_streams"
inputs = ["socket_tcp", "socket_udp"]
stream_name = "${VECTOR_AWS_KINESIS_STREAM_NAME}"
region = "${VECTOR_AWS_KINESIS_REGION}"
auth.access_key_id = "${VECTOR_AWS_KINESIS_ACCESS_KEY_ID}"
auth.secret_access_key = "${VECTOR_AWS_KINESIS_SECRET_ACCESS_KEY}"
encoding.codec = "json"

# Optional: Configure batching to optimize network usage
batch.max_bytes = 1024000
batch.timeout_secs = 1

# Retry settings
request.in_flight_limit = 5
request.retry_attempts = 10
request.timeout_secs = 30