name: Build & Push Meilisearch

on:
  push:
    branches:
      - 'main'

env:
  ORG_NAME: lostlink
  APP_NAME: meilisearch

jobs:
  should_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Detect File Changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Changed Files List
        run: |
          jq -r '.[]' $HOME/files.json

      - name: Filter and set Build Status
        id: build
        run: |
          unique_entries=$(jq -r '.[] | select(test("meilisearch"))' $HOME/files.json | awk -v RS=' ' '!a[$1]++')
          if [[ ! -z "$unique_entries" ]]
          then
            status="deploy"
          else
            status="skip"
          fi
          echo "status=$status" >> $GITHUB_OUTPUT
    outputs:
      status: ${{ steps.build.outputs.status }}

  deploy:
    runs-on: ubuntu-latest
    needs: should_deploy
    if: needs.should_deploy.outputs.status == 'deploy'

    strategy:
      fail-fast: false
      matrix:
        build:
          - {tag: "v0.30", platforms: "linux/arm64,linux/amd64"}
          - {tag: "v0.30.5", platforms: "linux/arm64,linux/amd64"}
          - {tag: "v1.0.2", platforms: "linux/arm64,linux/amd64"}
          - {tag: "v1.1.1", platforms: "linux/arm64,linux/amd64"}
          - {tag: "v1.2.1", platforms: "linux/arm64,linux/amd64"}
          - {tag: "v1.3.5", platforms: "linux/arm64,linux/amd64"}
          - {tag: "v1.4.2", platforms: "linux/arm64,linux/amd64"}
          - {tag: "v1.5.0", platforms: "linux/arm64,linux/amd64"}
          - {tag: "latest", platforms: "linux/arm64,linux/amd64"}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Import environment variables from a file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: 'docker.env'
          expand: 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.APP_NAME }}"
          platforms: ${{ matrix.build.platforms }}
          push: true
          tags: ${{ env.ORG_NAME }}/${{ env.APP_NAME }}:${{ matrix.build.tag }}
          build-args: |
            "MEILISEARCH_TAG=${{ matrix.build.tag }}"
