name: Build & Push Mysql

on:
  push:
    branches:
      - 'main'

env:
  ORG_NAME: lostlink
  APP_NAME: mysql

jobs:
  should_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Detect File Changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Changed Files List
        run: |
          jq -r '.[]' $HOME/files.json

      - name: Filter and set Build Status
        id: build
        run: |
          unique_entries=$(jq -r '.[] | select(test("mysql"))' $HOME/files.json | awk -v RS=' ' '!a[$1]++')
          if [[ ! -z "$unique_entries" ]]
          then
            status="deploy"
          else
            status="skip"
          fi
          echo "status=$status" >> $GITHUB_OUTPUT
    outputs:
      status: ${{ steps.build.outputs.status }}

  deploy:
    runs-on: ubuntu-latest
    needs: should_deploy
    if: needs.should_deploy.outputs.status == 'deploy'

    strategy:
      fail-fast: false
      matrix:
        build:
          - {tag: "5.7", platforms: "linux/amd64"}
          - {tag: "8.0", platforms: "linux/arm64,linux/amd64"}
          - {tag: "8.0.35", platforms: "linux/arm64,linux/amd64"}
          - {tag: "latest", platforms: "linux/arm64,linux/amd64"}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Import environment variables from a file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: 'docker.env'
          expand: 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ env.APP_NAME }}"
          platforms: ${{ matrix.build.platforms }}
          push: true
          tags: ${{ env.ORG_NAME }}/${{ env.APP_NAME }}:${{ matrix.build.tag }}
          build-args: |
            "MYSQL_TAG=${{ matrix.build.tag }}"
            "TIMEZONE=${{ env.TIMEZONE }}"
