name: Build & Push Redis

on:
  push:
    branches:
      - 'main'

jobs:
  redis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag:
          - "6.0"
          - "7.0"
          - "latest"

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Import environment variables from a file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env'
          expand: 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:redis"
          platforms: "linux/arm64,linux/amd64"
          push: true
          tags: lostlink/redis:${{ matrix.tag }}
          build-args: |
            "REDIS_TAG=${{ matrix.tag }}"